### ISSUE TITLE
Does not work on 2.0.4

### ISSUE THREAD

**Issue by jasir** [undx/redmine_screenshot_paste#1]
Probably because JQuery is needed?

**Comment by undx** [comment]
The javascript call isn't compatible with Redmine 2.0 (prototype).
I will fix it as soon as possible to be at least Redmine 2.0 AND 2.1 compatible.

**Comment by undx** [comment]
Should work on 2.0.x now.

**Comment by jasir** [comment]
Perfects, works very nice! Thank you a lot!
