### ISSUE TITLE
Does not work on 2.1.2

### ISSUE THREAD

**Issue by hsuzukih** [undx/redmine_screenshot_paste#5]
I put on files to plugin directory.  Reboot Server. After that , I could not open old tickets.

 Redmine version                          2.1.2.stable
  Ruby version                             1.8.7 (x86_64-linux)
  Rails version                            3.2.8
  Environment                              production
  Database adapter                         MySQL

**Comment by undx** [comment]
Can i have your application's log ? ... and the installed plugins.

**Comment by hsuzukih** [comment]
Thanks for your reply.

Yes sure.
I am useing bitnami virtual machine on ESX server.

I put on folder on plugins directory. 
Restart Redmine. 
Result is " 404 error"

Processing by IssuesController#new as HTML
  Parameters: {"project_id"=>"mis12"}
  Current user: hsuzukih (id=4)
  Rendered issues/_form_custom_fields.html.erb (18.9ms)
  Rendered issues/_attributes.html.erb (300.5ms)
  Rendered issues/_form.html.erb (347.5ms)
  Rendered issues/new.html.erb within layouts/base (359.9ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (1.0ms)
Completed 404 Not Found in 1023ms (Views: 25.8ms | ActiveRecord: 10.1ms)
