### ISSUE TITLE
Does not work on 2.1.3

### ISSUE THREAD

**Issue by vector3d** [undx/redmine_screenshot_paste#6]
Installed on Bitnami Stack 2.1.3 Windows
"New Issue" tab gets error:
404 "The page you were trying to access doesn't exist or has been removed."

**Comment by undx** [comment]
Hello, do you have other plugins installed ? Which ones (name+version) ? The log will be useful too !

**Comment by vector3d** [comment]
Hi,

no, no other plugins installed.

The log (I have removed SQL logging from):

Started GET "/redmine/projects/airsupply-2_0-sp1/issues/new" for 127.0.0.1 at 2012-11-23 11:31:07 +0100
Processing by IssuesController#new as HTML
  Parameters: {"project_id"=>"airsupply-2_0-sp1"}

<sqls removed from here (debug log level). I think you do not need it(?)>

  Rendered issues/_form_custom_fields.html.erb (187.5ms)
  Rendered issues/_attributes.html.erb (265.6ms)
  Rendered issues/_form.html.erb (312.5ms)
  Rendered issues/new.html.erb within layouts/base (312.5ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (0.0ms)

<sqls removed from here (debug log level). I think you do not need it(?)>

Completed 404 Not Found in 609ms (Views: 15.6ms | ActiveRecord: 46.9ms)

**Comment by undx** [comment]
Hi, 
that's strange, all current issues are Bitnami based (also on windows)...
I've just downloaded the bitnami Redmine stack (Windows version) in release 2.1.3. and ran it without any custom setting.

For what i've seen and tested without any modification: 
- the `issues` views are working fine, no missing template as you.
- the jar _isn't_ loading thus the screenshot capability isn't working.

To make it working, i had to hardcode the asset path in `_screenshot.html.erb` as : 

```
<param name="codebase" value="/redmine/plugin_assets/redmine_screenshot_paste/" />
```

Then i restarted Bitnami stack and everything went well. The plugin is fully working...

A few questions: 
- did you customize anything ?
- do you have the latest version of this plugin ? Look at [this](https://github.com/undx/redmine_screenshot_paste/pull/4)

Any other information is welcomed because i don't have the same behaviour as you with the same Bitnami stack...

**Comment by vector3d** [comment]
Hello,

I think, I downloaded the last version three days ago, because:
The README.md from plugin contains the line:
This plugin is compatible and has been tested with Redmine 2.0.x and 2.1.x.

What I did:
Downloaded/Installed Bitnami Stack 2.1.3
Loaded DB dump, which was created on Bitnami Stack 2.1.2.
Started the system and tested. Two users played a bit with Issues (custom fields, status and so on), created new issues too. We did standard actions (email notification/ created and configurated projects, subprojects, users, roles, issues, wiki, filesystem repository)... What else? I raised the Maximum attachment size to 64MB :-) We plan to use redmine hence tested a lot of standard user actions.

I downloaded the plugin as .zip file, unzipped it to D:\redmine\apps\redmine\htdocs\plugins
and restarted redmines.

After it, the New Issues tab did not work.
(The Admin->Plugins shown one plugin = the clipboard paste plugin)

Since I removed plugin, New issues tab works fine again.

This plugin is really helpful we would like to use "clipboard paste" in this new system...
Which kind of info can help you to identify the problem? I'm new in ruby and RedMine world...

**Comment by vector3d** [comment]
If I trying to open an existing Issue, the RedMine (with plugin) gets the 404 error and logs:

Started GET "/redmine/issues/4" for 127.0.0.1 at 2012-11-26 08:44:23 +0100
Processing by IssuesController#show as HTML
  Parameters: {"id"=>"4"}
  Current user: TestUser (id=19)
  Rendered issues/_action_menu.html.erb (15.6ms)
  Rendered issue_relations/_form.html.erb (0.0ms)
  Rendered issues/_relations.html.erb (15.6ms)
  Rendered issues/_history.html.erb (0.0ms)
  Rendered issues/_action_menu.html.erb (15.6ms)
  Rendered issues/_form_custom_fields.html.erb (15.6ms)
  Rendered issues/_attributes.html.erb (62.5ms)
  Rendered issues/_form.html.erb (93.8ms)
  Rendered issues/_edit.html.erb (93.8ms)
  Rendered issues/show.html.erb within layouts/base (171.9ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (0.0ms)
Completed 404 Not Found in 297ms (Views: 15.6ms | ActiveRecord: 15.6ms)

**Comment by bdecarne** [comment]
Same here ! With just this plugin. Classic installation on Debian.

  Rendered issues/_relations.html.erb (187.6ms)
  Rendered issues/_action_menu.html.erb (7.4ms)
  Rendered issues/_form_custom_fields.html.erb (1.2ms)
  Rendered issues/_attributes.html.erb (232.8ms)
  Rendered issues/_form.html.erb (274.5ms)
  Rendered issues/_edit.html.erb (282.7ms)
  Rendered issues/show.html.erb within layouts/base (565.5ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (1.0ms)
Completed 404 Not Found in 2447ms (Views: 32.4ms | ActiveRecord: 9.5ms)

**Comment by undx** [comment]
Hi, sorry for the late answer i didn't have much time...
Can you try to use the initial code in `init.rb` (first commit without leading path): 

```
render_on :view_issues_form_details_bottom, :partial => 'screenshot'
```

On debian, are you using a specific ruby web server ou just webrick. In that case, can you try with webrick: 

```
$ RAILS_ENV=production rails s  
```

Thanks for your feedback !

**Comment by bdecarne** [comment]
Found : the plugin directory was named "redmine_screenshot_paste-master". Renamed to redmine_screenshot_paste fixed it.

Sorry for wasting ur time.

Blaise

**Comment by undx** [comment]
@bdecarne :  No problem !
I think that i need to specify it on the README, it was obvious for me ...

@vector3d : Haven't you done the same thing ? Wrong plugin's directory name...

**Comment by vector3d** [comment]
Hello,

yes the dir name was the problem.
An advice in readme.rb about dir name is good idea!

The changing of  _screenshot.html.erb too, as you described, was needed too.

Thanks you very much! QA  people like this plugin :-)

**Comment by undx** [comment]
Good !
README.md was modified.

Last question, if you have time... Can you confirm me that the latest `init.rb` doesn't work on your release ?

I mean : 

```
render_on :view_issues_form_details_bottom, :partial => 'issues/screenshot'
```

I ask that because i've tested it (OSX, Windows, FreeBSD) and it should normally work.

Thanks for your feedback.
