### ISSUE TITLE
Redmine 2.0.3 Missing partial issues/screenshot

### ISSUE THREAD

**Issue by redmine-fr33520** [undx/redmine_screenshot_paste#7]
I tried to install 2.x plugin on Redmine 2.0.3 (BitNami release)
just install on plugin folder
when i open a new ticket, i have an error.

See log entries :

Started GET "/redmine/projects/titus/issues/new" for 127.0.0.1 at Fri Nov 23 09:52:39 +0100 2012
Processing by IssuesController#new as HTML
  Parameters: {"project_id"=>"titus"}
  Rendered issues/_form_custom_fields.html.erb (259.0ms)
  Rendered issues/_attributes.html.erb (361.0ms)
  Rendered issues/_form.html.erb (494.0ms)
  Rendered issues/new.html.erb within layouts/base (541.0ms)
Completed 500 Internal Server Error in 831ms

ActionView::Template::Error (Missing partial issues/screenshot with {:handlers=>[:rjs, :rsb, :erb, :builder], :locale=>[:fr, :en], :formats=>[:html]}. Searched in:
- "C:/Program Files/BitNami Redmine Stack/apps/redmine/htdocs/app/views"
  ):
  44:   <%= render :partial => 'issues/attributes' %>
  45: </div>
  46: 
  47: <%= call_hook(:view_issues_form_details_bottom, { :issue => @issue, :form => f }) %>
  48: <% end %>
  lib/redmine/hook.rb:111:in `send'
  lib/redmine/hook.rb:111:in`view_issues_form_details_bottom'
  lib/redmine/hook.rb:61:in `send'
  lib/redmine/hook.rb:61:in`call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in`call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in`call_hook'
  lib/redmine/hook.rb:158:in `call_hook'
  app/views/issues/_form.html.erb:47:in`_app_views_issues__form_html_erb___941061929_91321152'
  app/helpers/application_helper.rb:957:in `labelled_fields_for'
  app/views/issues/_form.html.erb:1:in`_app_views_issues__form_html_erb___941061929_91321152'
  app/views/issues/new.html.erb:11:in `_app_views_issues_new_html_erb___639076534_91428948'
  app/helpers/application_helper.rb:950:in`labelled_form_for'
  app/views/issues/new.html.erb:5:in `_app_views_issues_new_html_erb___639076534_91428948'
  app/controllers/issues_controller.rb:130:in`new'
  app/controllers/issues_controller.rb:129:in `new'

**Comment by undx** [comment]
Hello, do you have other plugins installed ? Which ones (name+version) ?

**Comment by redmine-fr33520** [comment]
Sorry I don't know how to catch plugin's version (sql? commande line).
I try reinstall Bitnami package but I have same problem.
Regards,
Olivier

System Win 7.
- Redmine 2.0.3
- Apache 2.2.22
- ImageMagick 6.5.6-8-Q8
- MySQL 5.0.83
- Subversion 1.7.4
- Git 1.7.9
- Ruby 1.8.7-p358-i386-mingw32
- Rails 2.3.14
- RubyGems 1.6.2

acts_as_activity_provider
acts_as_attachable
acts_as_customizable
acts_as_event
acts_as_list
acts_as_searchable
acts_as_tree
acts_as_versioned
acts_as_watchable
awesome_nested_set
classic_pagination
gravatar
open_id_authentication
prototype_legacy_helper
redmine_screenshot_paste-master
rfpdf

**Comment by undx** [comment]
Hello,
can you check if you're not in [this case](https://github.com/undx/redmine_screenshot_paste/issues/6#issuecomment-10867586)

**Comment by redmine-fr33520** [comment]
Hello,
Sorry, i tried the case #6 unsuccesfully.
Thanks for your help.

## Results:

ActionView::Template::Error (Missing partial issues/screenshot with {:handlers=>[:rjs, :rsb, :erb, :builder], :locale=>[:fr, :en], :formats=>[:html]}. Searched in:
- "C:/Program Files/BitNami Redmine Stack/apps/redmine/htdocs/app/views"
  ):
  44:   <%= render :partial => 'issues/attributes' %>
  45: </div>
  46: 
  47: <%= call_hook(:view_issues_form_details_bottom, { :issue => @issue, :form => f }) %>
  48: <% end %>
  lib/redmine/hook.rb:111:in `send'
  lib/redmine/hook.rb:111:in`view_issues_form_details_bottom'
  lib/redmine/hook.rb:61:in `send'
  lib/redmine/hook.rb:61:in`call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in`call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in`call_hook'
  lib/redmine/hook.rb:158:in `call_hook'
  app/views/issues/_form.html.erb:47:in`_app_views_issues__form_html_erb___269831045_93546960'
  app/helpers/application_helper.rb:957:in `labelled_fields_for'
  app/views/issues/_form.html.erb:1:in`_app_views_issues__form_html_erb___269831045_93546960'
  app/views/issues/new.html.erb:11:in `_app_views_issues_new_html_erb___472124251_93809256'
  app/helpers/application_helper.rb:950:in`labelled_form_for'
  app/views/issues/new.html.erb:5:in `_app_views_issues_new_html_erb___472124251_93809256'
  app/controllers/issues_controller.rb:130:in`new'
  app/controllers/issues_controller.rb:129:in `new'

**Comment by redmine-fr33520** [comment]
-Solved !-
- Fix #6 applied
- Wrong plugin folder.
  C:\Program Files\BitNami Redmine Stack\apps\redmine\htdocs\plugins.

Thanks for your help and for your work.

**Comment by undx** [comment]
Hello, 

so your problem was the same as [#issue6](https://github.com/undx/redmine_screenshot_paste/issues/6) ?

Regards !
