### ISSUE TITLE
No image display

### ISSUE THREAD

**Issue by ClementAndrieuCargo** [undx/redmine_screenshot_paste#9]
hello,
I've installed your plugin, every thing is OK but when i click on  "Drag or paste..." after i've done a screen shot, the "Name / Description" part show up but there is nothing between this part and the "Drag or paste..." button.

I've checked on FireFox, Chome and IE for the same result and Java is up to date. 
If someone can help me, i thank you in advance.

PS : Sorry if my english is not perfect, i'm french, i hope you'll understand my problem.

**Comment by undx** [comment]
Hello,

first a few questions:
- what's your Redmine version ?
- Do you have any errors in your logs ? (if so then include them in reply)
- Which JRE is installed ?
- Java is enabled on all browsers ?

Can you check that the jar is present in the following directory : 

```
plugin_assets/redmine_screenshot_paste/simageuploadapplet.jar
```

Can you enable the **java console** and give me the log after you clicked on the `Drag or paste from clipboard(Full screen: PrintScreen, Active Window: Alt+PrintScreen)` link.

PS: Pas de soucis, je suis français aussi ! ;)

**Comment by ClementAndrieuCargo** [comment]
(merci d'avoir répondu aussi vite ... je continue en anglais pour les anglophones)

My Redmine version is Bitnani Installer version 2.1.2 on a 2008 R2 Windows Server (64bit so)
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

My Logs - Production.log : 

Started GET "/redmine/settings" for 127.0.0.1 at Thu Dec 13 10:47:43 +0100 2012
Processing by SettingsController#index as HTML
  Current user: manager (id=6)
  Rendered settings/_general.html.erb (15.6ms)
  Rendered settings/_display.html.erb (15.6ms)
  Rendered settings/_authentication.html.erb (0.0ms)
  Rendered settings/_projects.html.erb (31.2ms)
  Rendered queries/_columns.html.erb (31.2ms)
  Rendered settings/_issues.html.erb (31.2ms)
  Rendered settings/_notifications.html.erb (15.6ms)
  Rendered settings/_mail_handler.html.erb (0.0ms)
SCM command failed, make sure that your SCM command (e.g. svn) is in PATH (C:\Redmine\imagemagick\;C:/Redmine/ruby/lib/ruby/gems/1.8/bin;C:\Perl\site\bin;C:\Perl\bin;C:\Perl64\site\bin;C:\Perl64\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Redmine/git/bin;C:\Redmine/subversion/bin;C:\Redmine\imagemagick)
You can configure your scm commands in config/configuration.yml.
"darcs" --version
with: No such file or directory - "darcs" --version
scm: error during get scm available: No such file or directory - "darcs" --version
SCM command failed, make sure that your SCM command (e.g. svn) is in PATH (C:\Redmine\imagemagick\;C:/Redmine/ruby/lib/ruby/gems/1.8/bin;C:\Perl\site\bin;C:\Perl\bin;C:\Perl64\site\bin;C:\Perl64\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Redmine/git/bin;C:\Redmine/subversion/bin;C:\Redmine\imagemagick)
You can configure your scm commands in config/configuration.yml.
"darcs" --version
with: No such file or directory - "darcs" --version
scm: error during get version string: No such file or directory - "darcs" --version
SCM command failed, make sure that your SCM command (e.g. svn) is in PATH (C:\Redmine\imagemagick\;C:/Redmine/ruby/lib/ruby/gems/1.8/bin;C:\Perl\site\bin;C:\Perl\bin;C:\Perl64\site\bin;C:\Perl64\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Redmine/git/bin;C:\Redmine/subversion/bin;C:\Redmine\imagemagick)
You can configure your scm commands in config/configuration.yml.
"hg" --version
with: No such file or directory - "hg" --version
scm: error during get scm available: No such file or directory - "hg" --version
SCM command failed, make sure that your SCM command (e.g. svn) is in PATH (C:\Redmine\imagemagick\;C:/Redmine/ruby/lib/ruby/gems/1.8/bin;C:\Perl\site\bin;C:\Perl\bin;C:\Perl64\site\bin;C:\Perl64\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Redmine/git/bin;C:\Redmine/subversion/bin;C:\Redmine\imagemagick)
You can configure your scm commands in config/configuration.yml.
"hg" --version
with: No such file or directory - "hg" --version
scm: error during get version string: No such file or directory - "hg" --version
SCM command failed, make sure that your SCM command (e.g. svn) is in PATH (C:\Redmine\imagemagick\;C:/Redmine/ruby/lib/ruby/gems/1.8/bin;C:\Perl\site\bin;C:\Perl\bin;C:\Perl64\site\bin;C:\Perl64\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Redmine/git/bin;C:\Redmine/subversion/bin;C:\Redmine\imagemagick)
You can configure your scm commands in config/configuration.yml.
"cvs" --version
with: No such file or directory - "cvs" --version
scm: error during get scm available: No such file or directory - "cvs" --version
SCM command failed, make sure that your SCM command (e.g. svn) is in PATH (C:\Redmine\imagemagick\;C:/Redmine/ruby/lib/ruby/gems/1.8/bin;C:\Perl\site\bin;C:\Perl\bin;C:\Perl64\site\bin;C:\Perl64\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Redmine/git/bin;C:\Redmine/subversion/bin;C:\Redmine\imagemagick)
You can configure your scm commands in config/configuration.yml.
"cvs" --version
with: No such file or directory - "cvs" --version
scm: error during get version string: No such file or directory - "cvs" --version
SCM command failed, make sure that your SCM command (e.g. svn) is in PATH (C:\Redmine\imagemagick\;C:/Redmine/ruby/lib/ruby/gems/1.8/bin;C:\Perl\site\bin;C:\Perl\bin;C:\Perl64\site\bin;C:\Perl64\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Redmine/git/bin;C:\Redmine/subversion/bin;C:\Redmine\imagemagick)
You can configure your scm commands in config/configuration.yml.
"bzr" --version
with: No such file or directory - "bzr" --version
scm: error during get scm available: No such file or directory - "bzr" --version
SCM command failed, make sure that your SCM command (e.g. svn) is in PATH (C:\Redmine\imagemagick\;C:/Redmine/ruby/lib/ruby/gems/1.8/bin;C:\Perl\site\bin;C:\Perl\bin;C:\Perl64\site\bin;C:\Perl64\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Redmine/git/bin;C:\Redmine/subversion/bin;C:\Redmine\imagemagick)
You can configure your scm commands in config/configuration.yml.
"bzr" --version
with: No such file or directory - "bzr" --version
scm: error during get version string: No such file or directory - "bzr" --version
  Rendered settings/_repositories.html.erb (312.0ms)
  Rendered common/_tabs.html.erb (452.4ms)
  Rendered settings/edit.html.erb within layouts/admin (452.4ms)
  Rendered admin/_menu.html.erb (15.6ms)
  Rendered layouts/base.html.erb (15.6ms)
Completed 200 OK in 499ms (Views: 452.4ms | ActiveRecord: 31.2ms)

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
error.log :
[Thu Dec 13 09:11:00 2012] [error] [client 192.168.0.1] File does not exist: C:/Redmine/apache2/htdocs/plugin_assets
[Thu Dec 13 09:11:00 2012] [error] [client 192.168.0.1] File does not exist: C:/Redmine/apache2/htdocs/plugin_assets

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

No JRE installed on this server, which one version must i'll installed ? (i think, i must update my path after)

Java 7u7 64 bit and 32bit is installed on my test client, i used for my test ie9, chrome 23.0. and mozilla 12.0.  

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

simageuploadapplet.jar is present in "apps\redmine\htdocs\public\plugin_assets\redmine_screenshot_paste"

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

java console : 

ClassNotFoundExeption
imageuploadapplet.Main

Plug-in Java 10.7.2.11
Utilisation de la version JRE 1.7.0_07-b11 Java HotSpot(TM) Client VM
Répertoire d'origine de l'utilisateur = C:\Users*****

---

c:   effacer la fenêtre de la console
f:   finaliser les objets de la file d'attente de finalisation
g:   nettoyer la mémoire
h:   afficher ce message d'aide
l:   vider la liste des chargeurs de classes
m:   imprimer le relevé d'utilisation de la mémoire
o:   déclencher la journalisation
q:   masquer la console
r:   recharger la configuration des règles
s:   vider les propriétés système et de déploiement
t:   vider la liste des threads
v:   vider la pile des threads
x:   effacer le cache de chargeurs de classes
0-5: fixer le niveau de trace à <n>

---

**Comment by undx** [comment]
No need to install a JRE on the server.

Obviously, you server don't known where to get the asset...
I really think that Bitnami is a pain in the ass !!!
Please, have a look at this [comment](https://github.com/undx/redmine_screenshot_paste/issues/6#issuecomment-10657365) and tell me if it worked.

**Comment by undx** [comment]
No reply => closing
